// <auto-generated />
using G_Scores.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G_Scores.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241125162433_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("G_Scores.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("dia_li")
                        .HasColumnType("float");

                    b.Property<double?>("gdcd")
                        .HasColumnType("float");

                    b.Property<double?>("hoa_hoc")
                        .HasColumnType("float");

                    b.Property<double?>("lich_su")
                        .HasColumnType("float");

                    b.Property<string>("ma_ngoai_ngu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ngoai_ngu")
                        .HasColumnType("float");

                    b.Property<double?>("ngu_van")
                        .HasColumnType("float");

                    b.Property<string>("sbd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("sinh_hoc")
                        .HasColumnType("float");

                    b.Property<double?>("toan")
                        .HasColumnType("float");

                    b.Property<double?>("vat_li")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("dia_li");

                    b.HasIndex("gdcd");

                    b.HasIndex("hoa_hoc");

                    b.HasIndex("lich_su");

                    b.HasIndex("ngoai_ngu");

                    b.HasIndex("ngu_van");

                    b.HasIndex("sinh_hoc");

                    b.HasIndex("toan");

                    b.HasIndex("vat_li");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
